export const companies = [
  {
    company_name: "Infosys",
    email: "management@infosys.com",
    phone_no: "+91 9563214587",
    contact_person: "Vijayent Roy ",
    facilitator: "--",
    Sites: "12",
    tenants: "--",
    tenant_groups: "--",
  },
  {
    company_name: "Wipro",
    email: "management@wipro.com",
    phone_no: "+91 9834687423",
    contact_person: "Kalpit Soni ",
    facilitator: "--",
    Sites: "8",
    tenants: "--",
    tenant_groups: "--",
  },
  {
    company_name: "Accenture ",
    email: "management@accenture .com",
    phone_no: "+91 8732654789",
    contact_person: "Drishti Sane ",
    facilitator: "--",
    Sites: "4",
    tenants: "--",
    tenant_groups: "--",
  },
  {
    company_name: "Capgemini ",
    email: "management@capgemini  .com",
    phone_no: "+91 8432657995",
    contact_person: "Aisha Keer ",
    facilitator: "--",
    Sites: "6",
    tenants: "--",
    tenant_groups: "--",
  },
  {
    company_name: "Lodha",
    email: "management@lodha.com",
    phone_no: "+91 9642357894",
    contact_person: "Kanika Khare",
    facilitator: "--",
    Sites: "24",
    tenants: "16",
    tenant_groups: "--",
  },
  {
    company_name: "Tata Consultancy Services",
    email: "management@tcs.com",
    phone_no: "+91 9632457468",
    contact_person: "Prabhat Rao ",
    facilitator: "--",
    Sites: "10",
    tenants: "--",
    tenant_groups: "--",
  },
  {
    company_name: "HCL",
    email: "management@hcl.com",
    phone_no: "+91 9452136487",
    contact_person: "Venkat Pant",
    facilitator: "--",
    Sites: "5",
    tenants: "2",
    tenant_groups: "1",
  },
  {
    company_name: "Redington ",
    email: "management@redington.com",
    phone_no: "+91 9326571865",
    contact_person: "Samir Yadav",
    facilitator: "--",
    Sites: "1",
    tenants: "1",
    tenant_groups: "--",
  },
  {
    company_name: "Mphasis ",
    email: "management@mphasis.com",
    phone_no: "+91 9874621547",
    contact_person: "Sweta Chawla",
    facilitator: "--",
    Sites: "1",
    tenants: "--",
    tenant_groups: "--",
  },
  {
    company_name: "Larsen & Toubro",
    email: "management@larsentoubro.com",
    phone_no: "+91 9547154964",
    contact_person: "Abhishek Kumar",
    facilitator: "--",
    Sites: "16",
    tenants: "--",
    tenant_groups: "--",
  },
];
